# zizmor finds potential security vulnerabilities in GitHub workflow
# files. Documentation: https://woodruffw.github.io/zizmor

rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        astral-sh/setup-uv: ref-pin
        codecov/codecov-action: ref-pin
        conda-incubator/setup-miniconda: ref-pin
        mamba-org/setup-micromamba: ref-pin
        heliophysicsPy/pyhc-actions/*: ref-pin
        pypa/*: ref-pin
        scientific-python/*: ref-pin
        ts-graphviz/setup-graphviz: ref-pin

# Put settings that we intend to fix later on below this line. If we
# decide that a potential security vulnerability does not necessitate a
# fix, append a comment like `# zizmor: ignore[unpinned-uses]` to the
# line or set the appropriate configuration options above.
