[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.12.5,<0.13" ]

[project]
name = "pyfaradaycup"
version = "0.1.0"
description = "Tools for data pipelines and data analysis for Faraday cups"
readme = "README.md"
authors = [
  { name = "Kristoff Paulson" },
  { name = "Mike Stevens" },
  { name = "Joy Velasquez" },
  { name = "Nick Murphy", email = "namurphy@cfa.harvard.edu" },
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "astropy>=3",
  "plasmapy>=0.3.1",
]

[dependency-groups]
dev = [
  { include-group = "lint" },
  { include-group = "nox" },
  { include-group = "test" },
  { include-group = "typecheck" },
  { include-group = "zizmor" },
]
test = [
  "pytest>=9.1",
  "pytest-filter-subpackage>=0.2",
  "pytest-xdist>=3.8",
]
lint = [
  "pre-commit>=4.6.2",
]
nox = [
  "nox>=2026.8.10",
  "nox-uv>=0.8",
]
typecheck = [
  "ty>=0.0.74",
]
zizmor = [
  "zizmor>=1.29",
]
docs = [
    "sphinx>=9.1.0",
]

[tool.pytest]  # https://docs.pytest.org/en/stable/reference/customize.html#pyproject-toml
addopts = [
  "--dist=loadfile",
  "--durations=5",
  "--durations-min=0.4",
  "--numprocesses=auto",
  "--tb=short",
]
empty_parameter_set_mark = "fail_at_collect"
filterwarnings = [
  # To prevent the number of warnings issue during tests from ballooning,
  # treat warnings as errors unless otherwise specified. Please raise a
  # GitHub issue when ignoring a FutureWarning or DeprecationWarning,
  # and label it with "needed for release".
  "error",
]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
strict = true
testpaths = [ "tests", "src/pyfaradaycup" ]
